---
stages:
  - test
  - publish

include:
  - remote: "https://gitlab.com/dudefellah/ci-templates/-/raw/master/ansible/Molecule.gitlab-ci.yml"
  - remote: "https://gitlab.com/dudefellah/ci-templates/-/raw/master/ansible/Galaxy.gitlab-ci.yml"

molecule:
  stage: test
  image: dudefellah/ansible-molecule
  extends: .ansible_molecule
  tags:
    - docker-socket-runner
  allow_failure: true

publish:
  stage: publish
  image: ansible/ansible-runner:latest
  extends: .ansible_galaxy_publish
  tags:
    - docker-socket-runner
